#指定端口号
server:
  port: 9000
#加载mybatis的映射文件
#配置包的别名
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.lzy.blog.pojo

#配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://39.106.88.87:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: liu123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB #单个文件上传的大小
      max-request-size: 100MB
  #mongodb配置
  data:
    mongodb:
      host: 39.106.88.87
      database: blog
#fasfdfs的配置
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 39.106.88.87:22122
upload:
  base-url: http://39.106.88.87/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg